### ISSUE TITLE
ability to output --make-digest result to stdout, or other way to fetch digest from changed remote file

### ISSUE THREAD

**Issue by damienvancouver** [nethappen/blocksync-fast#3]
I have been testing blocksync-fast and it has been fantastic so far!  Thank you for all your hard work!

I have run into a use case that is not elegantly handled.  I would like to be able to run a blocksync-fast to an existing (possibly changed) remote file.  I was able to accomplish this by making a digest on the remote side, transferring it to the local side, and using it for my -f switch.  :

1. Perform an initial clone of the block device to the remote location (with blocksync-fast, rsync, or dd, anything)
2. The remote location may change (e.g. it gets mounted remotely and changes are made).  OR, the digest file from the initial clone is lost.  OR the initial clone was made with dd, rsync or another tool.
3. We need an up-to-date digest file of the destination, so  on the remote destination, create a digest file with:  `ssh user@remote "blocksync-fast --make-digest -s /dev/vg/dest_vol -f /tmp/vol.digest"`
4. scp _vol.digest_ down to my local device:     `scp user@remote:/tmp/vol.digest /tmp/`
5. run blocksync-fast using this digest to undo/rollback any changes on the destination:  `blocksync-fast -s /dev/vg/src_vol -f /tmp/vol.digest --make-delta | ssh user@remote "blocksync-fast --apply-delta -d /dev/vg/dest_vol"`

If --make-digest could output to stdout, then this could be done with one less step (ie. missing the scp step).  We could replace steps 3 and 4 with:  `ssh user@remote "blocksync-fast --make-digest -s /dev/vg/dest_vol -f -" > /tmp/vol.digest`

I tried using - as an value to -f switch, but was unable to get a working digest file out of it.. e.g. `blocksync-fast --make-digest -f - > digestfile` created an invalid digest file without the correct size.  Maybe -f could allow -, or if --make-digest is specified without a -f switch, it could output to stdout (like --make-delta works)?

Hopefully this would be a pretty minor change, if this all makes sense.  Thanks again for this amazing utility!

**Comment by nethappen** [comment]
You understand the idea of ​​the program well. For fast synchronization between remote block devices, you using the Digest file, which is generated locally and sent to the other side.

Of course, the STDOUT functionality for the make-digest operation is easy to implement and I will try to include it as soon as possible.

Out of curiosity, I ask, your use case is restoring a VPS server to a previously saved state from a previously made copy or original image, do I understand correctly?

**Comment by damienvancouver** [comment]
Hi, the use case for this was actually more for edge cases.   I work at a small hosting company and so I suspect I have all the same unaddressed needs that led you to write bocksync-fast in the first place, so I bet this will sound familiar :)

1. updating an older backup / clone of a VPS, when the digest file is no longer around. 
 Even though  I'm expecting to always have my digest file from past runs in normal circumstances (like regular scheduled backups and migrations), there are edge cases and one-offs where sometimes we copy or clone stuff by hand.  For example, maybe we clone a server for a customer and they use it for testing/etc for a while, then need it synced up from their live server (and we didn't save the delta anywhere because it was a one-off operation from a support ticket).   

2.  The actual use case I was looking at yesterday was when I accidentally mounted my destination volume in the destination, without using `-o ro` .  Oops!!!  I realized immediately that my digest was no longer correct, which led me to try the other method (taking the dest digest back to the source).  and of ocurse that worked so well because blocksync-fast is so clever!   

I think your approach with blocksync-fast and the ability to save and re-use the digest plus do the deltas, and how it pipes UNIX-style through whatever transport is nothing short of brilliant work.  It's so great!    I also read through the source (I used to code C for work stuff a lifetime or two ago) and it is really tidy and great looking too.  It looks very polished and like you have been using it yourself in production for a quite a while!

Thanks in advanced for adding stdout to the make-digest, it's in no way urgent as it's an edge case thing... It wont' hold me up adding blocksync-fast support to my VM migration scripts and I'm super excited to implement automatic snapshot backups too.

**Comment by nethappen** [comment]
Hi, Your request has been added to version 1.0.6

You can use without -f parameter, then stdout will be default for --make-digest operation:
`blocksync-fast --make-digest -s /dev/vg/dest_vol > /tmp/vol.digest`
`blocksync-fast --make-digest -s /dev/vg/dest_vol | ssh 'cat - > copy_to_another_machine'`

**Comment by damienvancouver** [comment]
so great!  Thank you!!!   I have been doing lots of testing on my end, I've worked blocksync-fast into my VM migration scripts and it is working great, so much faster than when I was using rsync and waiting for the checksum calculation to run before the transfer would start.  I love it!!!!    I'm going to be setting up incremental snapshot backups of VM disks next, using some of the stuff from your scripts folder.

I've come across a couple other small things that I'll make issues for.. they are not urgent fixes any of them.  

And some other things I'd like to help with (if you'd like to pursue it) 
is getting a man page together and looking at how we'd get this into some OS packaging.  I use Debian for server stuff but also FC40 (actually asahi) and some Manjaro (arch), so I have some skills in those three.  

We would probably need a proper champion for each of these distros who can be the package maintainer.   I could definitely take that on for the Debian package, but i'm not a Debian developer (yet) so we'll see.  I can go onto their IRC though and see if I can get someone to sponsor me, once I get a package built.  :-)

Let me know if you're interested in that at all and I can make an issue for tracking it (we can start with a .deb).  What flavour of NIX do you run on your end?

**Comment by nethappen** [comment]
I'm really glad that blocksync-fast is useful and works successfully. Any suggestions are welcome and I will try to develop the project to be even more helpful.

Of course, any help in the development of the project is appreciated and contributions will be appreciated. I like your enthusiasm and that you are working on something that you think is good and works great.

You can report minor issues that you come across and I will take care of them.

It would be great to distribute it to various linux packages.
As for packaging, we can start with a .deb package for Debian - it would be a great starting point.

So far I have added every version to the Gentoo distribution to the user-created repository - GURU, but none of the Gentoo developers have merged it into the main branch yet.

I think it will be similar process for every Linux distribution. First you need to make your own packages and add them to the user-created repository appropriate for each distribution.
Something like GURU in Gentoo or AUR in Archlinux.

Then convince the core developers of the system to merge the program into the main branch of the repository.

I personally use Gentoo Linux on Desktop and on various customized solutions, such as my own network routers, Linux servers. I use Archlinux on Laptop. And Debian as Linux systems for standard VPS.
