### ISSUE TITLE
a way to output the source file to stdout when making digest (for initial copy to remote SSH destination)

### ISSUE THREAD

**Issue by damienvancouver** [nethappen/blocksync-fast#4]
When storing destinations on the other side of a SSH connection, I have to do two steps:

1. create the digest locally with:  `blocksync-fast --make-digest -s /dev/vg/src_vol -f src.digest`
2. copy the src_vol to the destination

Then subsequent copies can be made using --make-delta and --apply-delta

Currently I use dd for step 2, piped into a SSH command, e.g. `dd if=/dev/vg/src_vol bs=1M conv=sync,noerror | ssh user@remote "dd of=/dev/vg/dest_vol bs=1M"`

It would be handy though if blocksync could output the src_vol to STDOUT (like dd does) in the same step as it runs the make-digest.  I could then run a single command to make the digest and sync.

This could maybe work by allowing `-d -` to make the dest file STDOUT?   Then something like this would create the digest and do the initial copy:    `blocksync-fast -s /dev/vg/src_vol -f src.digest -d -  | ssh user@remote "dd of=/dev/vg/dest_vol bs=1M"`

**Comment by nethappen** [comment]
You can use this command from the very beginning:
# blocksync-fast --make-delta -s /dev/vg/src_vol -f src.digest | ssh user@remote 'blocksync-fast --apply-delta -d /dev/vg/dest_vol'

1. The first time it is used it will create a new digest file and simply copy the entire contents of src_vol to remote/dest_vol
2. You don't need to do --make-digest - the digest file will be created during the first use.
3. Each subsequent time you use this command, it will read from the created digest file and overwrite it with the data that has changed.
4. The delta file can also contain the entire source image - of course there is a small data overhead, 8 extra bytes for each data block, which at 30GiB of data and a 4K block size the overhead is 60MiB compared to natively transferring the image via dd

**Comment by damienvancouver** [comment]
Fantastic!  I guess I should have tested that first to see if it would just work!   I am going to be adding blocksync-fast support to my VM migration scripts this evening, I will do it this way.   I have many VM migrations to do so that I can do some hardware upgrades, and blocksync-fast will give me huge speed savings...   I am so excited for this tool which is just perfect for my needs (both on the migration front and also for providing deduplicated VM backups.  Currently I do filesystem backups with rsync but I want to complement that with automatic full disk snapshots too, and this is totally the best tool for that job.  Thank you again!
